salud/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path
from metricas import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('show/', views.show),
    path('', RedirectView.as_view(url='show', permanent=True)),
    path('diary', views.diary),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

metricas/models.py
from django.db import models

# Create your models here.


class Metrics(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)
    names = models.CharField(max_length=100)
    surnames = models.CharField(max_length=100)
    age = models.IntegerField()
    weight = models.FloatField()
    heartRate = models.IntegerField(
        help_text="Frecuencia Cardiaca(Heart Rate) medida en BPM(Beats per minute)/Pulsaciones por minuto")
    bloodOxygenSaturation = models.IntegerField(
        help_text="Saturación de Oxígeno en Sangre")

    STRESS_LEVEL = (
        ('low', 'Low'),
        ('moderate', 'Moderate'),
        ('high', 'High'),
        ('extreme', 'Extreme'),
    )

    stresslevel = models.CharField(
        max_length=20, choices=STRESS_LEVEL, default='low', help_text='Nivel de estrés')

    class Meta:
        db_table = "metrics"

metricas/forms.py
from django import forms
from metricas.models import Metrics


class MetricsForm(forms.ModelForm):
    class Meta:
        model = Metrics
        fields = "__all__"

metricas/views.py
from django.shortcuts import render

# Create your views here.

from django.shortcuts import render, redirect
from metricas.forms import MetricsForm
from metricas.models import Metrics
# Create your views here.


def diary(request):
    if request.method == "POST":
        form = MetricsForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = MetricsForm()
    return render(request, 'index.html', {'form': form})


def show(request):
    metric = Metrics.objects.all()
    return render(request, "show.html", {'metric': metric})


def edit(request, id):
    metrics = Metrics.objects.get(id=id)
    stressLevels = Metrics.STRESS_LEVEL
    return render(request, 'edit.html', {'metrics': metrics, 'stressLevels': stressLevels})


def update(request, id):
    metrics = Metrics.objects.get(id=id)
    form = MetricsForm(request.POST, instance=metrics)
    if form.is_valid():
        form.save()
        return redirect("/show")
    return render(request, 'edit.html', {'metrics': metrics})


def destroy(request, id):
    metrics = Metrics.objects.get(id=id)
    metrics.delete()
    return redirect("/show")

metricas/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Metrics</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

    <div class="container-fluid">

        <div class="col-12 mt-4 w-100">
            {% block content %}{% endblock %}
        </div>

    </div>
</body>

</html>

metricas/templates/edit.html
{% extends "base_generic.html" %}

{% block content %}
<form method="POST" class="post-form" action="/update/{{metrics.id}}">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Actualiza Detalles</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Nombres:</label>
            <div class="col-sm-4">
                <input type="text" name="names" id="id_names" required maxlength="100" value="{{ metrics.names }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Apellidos:</label>
            <div class="col-sm-4">
                <input type="text" name="surnames" id="id_surnames" required maxlength="100" value="{{ metrics.surnames }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Edad:</label>
            <div class="col-sm-4">
                <input type="number" name="age" id="id_age" required maxlength="3"
                    value="{{ metrics.age }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Peso:</label>
            <div class="col-sm-4">
                <input type="number" name="weight" id="id_weight" required maxlength="2"
                    value="{{ metrics.weight }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Ritmo cardiaco:</label>
            <div class="col-sm-4">
                <input type="number" name="heartRate" id="id_heartRate" required maxlength="3"
                    value="{{ metrics.heartRate }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Saturación de oxígeno en sangre:</label>
            <div class="col-sm-4">
                <input type="number" name="bloodOxygenSaturation" id="id_bloodOxygenSaturation" required maxlength="3"
                    value="{{ metrics.bloodOxygenSaturation }}" />
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Nivel de estrés:</label>
            <div class="col-sm-4">
                <select name="stresslevel" id="id_stresslevel">
                    {% for stressLevel in stressLevels %}
                        <option value="{{stressLevel.0}}"
                            {% if stressLevel.0 == metrics.stresslevel %}selected="selected"{% endif %}>
                            {{ stressLevel.1 }}
                        </option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-2">
                <button href="../../" class="btn btn-secondary">Volver</button>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

metricas/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<a href="show/">Volver</a>
<form method="POST" class="post-form" action="/diary">
    {% csrf_token %}
    <div class="container">
        <br>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-4">
                <h3>Ingresar Detalles</h3>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Nombres:</label>
            <div class="col-sm-4">
                {{ form.names }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Apellidos:</label>
            <div class="col-sm-4">
                {{ form.surnames }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Edad:</label>
            <div class="col-sm-4">
                {{ form.age }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Peso:</label>
            <div class="col-sm-4">
                {{ form.weight }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Ritmo cardiaco:</label>
            <div class="col-sm-4">
                {{ form.heartRate }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Saturación de oxígeno en sangre:</label>
            <div class="col-sm-4">
                {{ form.bloodOxygenSaturation }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Nivel de estrés:</label>
            <div class="col-sm-4">
                {{ form.stresslevel }}
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-sm-2">
                <button href="show/" class="btn btn-secondary">Volver</button>
            </div>
            <div class="col-sm-2">
                <button type="submit" class="btn btn-primary">Enviar</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

metricas/templates/show.html
{% extends "base_generic.html" %}

{% block content %}
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Edad</th>
            <th scope="col">Peso</th>
            <th scope="col">Ritmo cardiaco</th>
            <th scope="col">Saturación de oxígeno en sangre</th>
            <th scope="col">Nivel de estrés</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for metrics in metric %}
        <tr>
            <th scope="row">{{ metrics.id }}</th>
            <td>{{ metrics.names }}</td>
            <td>{{ metrics.surnames }}</td>
            <td>{{ metrics.age }}</td>
            <td>{{ metrics.weight }}</td>
            <td>{{ metrics.heartRate }}</td>
            <td>{{ metrics.bloodOxygenSaturation }}</td>
            <td>{{ metrics.stresslevel }}</td>
            <td class="d-flex justify-content-around">
                <a href="/edit/{{ metrics.id }}"><span class="glyphicon glyphicon-pencil">Editar</span></a>
                <a href="/delete/{{ metrics.id }}">Eliminar</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<br>
<br>
<center><a href="/diary" class="btn btn-primary">Añadir nuevo registro</a></center>
{% endblock %}